In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
import joblib

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_predict
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor
from numpy.linalg import eig

In [2]:
# import dataset
inputs = open("inputs.txt")
labels  = open("labels.txt")
data_set = []     
classes = []
for x ,y in zip(inputs ,labels):
    data_set.append(x.split(" "))
    classes.append(int(y))
row = len(data_set)
col = len(data_set[0])
for i in range(row):
    for j in range(col):
        data_set[i][j] = float(data_set[i][j])


In [3]:
# splitting data into training and test , when submitting use all data to train model
X_train, X_test, y_train, y_test = train_test_split(np.array(data_set), np.array(classes), test_size=0.3,random_state=50) # 70% training and 30% test

In [4]:
#using a logistic model 
logisticRegr = LogisticRegression(solver ='lbfgs' ,max_iter=500,tol=0.001 , random_state = 12 ,multi_class ='auto' ,warm_start =True )
logisticRegr.fit(X_train, y_train)
predict_test_lr = logisticRegr.predict(X_test)
print(confusion_matrix(y_test,predict_test_lr))
print(classification_report(y_test,predict_test_lr))

[[49  0  0  0  0  1  0  0  1  0]
 [ 2 58  0  0  0  0  1  0  0  0]
 [ 0  3 47  3  0  0  1  2  1  1]
 [ 1  2  2 44  0  4  1  3  3  1]
 [ 0  3  1  0 50  0  1  0  0  3]
 [ 0  1  0  1  1 46  2  0  1  1]
 [ 0  0  0  0  1  0 71  0  0  0]
 [ 1  0  3  1  1  0  0 55  2  3]
 [ 0  2  2  0  0  3  0  1 47  2]
 [ 1  0  0  2  4  1  0  2  1 52]]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93        51
           1       0.84      0.95      0.89        61
           2       0.85      0.81      0.83        58
           3       0.86      0.72      0.79        61
           4       0.88      0.86      0.87        58
           5       0.84      0.87      0.85        53
           6       0.92      0.99      0.95        72
           7       0.87      0.83      0.85        66
           8       0.84      0.82      0.83        57
           9       0.83      0.83      0.83        63

   micro avg       0.86      0.86      0.86       600
   macro avg       

In [5]:
joblib.dump(logisticRegr, 'logistic_Regression.pkl')

['logistic_Regression.sav']

In [6]:
trained_model = joblib.load('logistic_Regression.pkl')
predict_test_lr = trained_model.predict(X_test)
print(confusion_matrix(y_test,predict_test_lr))
print(classification_report(y_test,predict_test_lr))

[[49  0  0  0  0  1  0  0  1  0]
 [ 2 58  0  0  0  0  1  0  0  0]
 [ 0  3 47  3  0  0  1  2  1  1]
 [ 1  2  2 44  0  4  1  3  3  1]
 [ 0  3  1  0 50  0  1  0  0  3]
 [ 0  1  0  1  1 46  2  0  1  1]
 [ 0  0  0  0  1  0 71  0  0  0]
 [ 1  0  3  1  1  0  0 55  2  3]
 [ 0  2  2  0  0  3  0  1 47  2]
 [ 1  0  0  2  4  1  0  2  1 52]]
              precision    recall  f1-score   support

           0       0.91      0.96      0.93        51
           1       0.84      0.95      0.89        61
           2       0.85      0.81      0.83        58
           3       0.86      0.72      0.79        61
           4       0.88      0.86      0.87        58
           5       0.84      0.87      0.85        53
           6       0.92      0.99      0.95        72
           7       0.87      0.83      0.85        66
           8       0.84      0.82      0.83        57
           9       0.83      0.83      0.83        63

   micro avg       0.86      0.86      0.86       600
   macro avg       

0.13333333333333333